dubbo:
  scan:
    base-packages: com.ascrud.cloud.samples.product
  application:
    name: product-dubbo-provider
  protocols:
    dubbo:
      name: dubbo
      port: -1
  #    rest:
  #      name: rest
  #      port: 9090
  #      server: netty
  registry:
    #   The Spring Cloud Dubbo's registry extension
    address: nacos://${NACOS_SERVER_ADDR:192.168.0.135:8848}/?username=nacos&password=nacos
