version: '3.3'

services:
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/samples-eureka:0.2.0
    restart: on-failure
    networks:
      - samples
    ports:
      - "8762:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
  admin:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/samples-admin:0.2.0
    restart: on-failure
    networks:
      - samples
    ports:
      - "9093:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
  hystrix-dashboard:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/samples-hystrix-dashboard:0.2.0
    restart: on-failure
    networks:
      - samples
    ports:
      - "9094:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
  zuul:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/samples-zuul:0.2.0
    restart: on-failure
    networks:
      - samples
    ports:
      - "9090:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
    depends_on:
      - eureka
      - user
  user:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/user-server:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9095:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - eureka
      - admin
  product:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/product-server:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9092:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - eureka
      - admin
  order:
    image: registry.cn-hangzhou.aliyuncs.com/ascrud/order-server:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9091:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - eureka
      - admin

networks:
  samples:

volumes:
  mydata:
