dubbo:
  scan:
    base-packages: com.upcwangying.cloud.samples.product
  application:
    name: product-dubbo-provider
  protocols:
    dubbo:
      name: dubbo
      port: -1
  #    rest:
  #      name: rest
  #      port: 9090
  #      server: netty
  registry:
    #   The Spring Cloud Dubbo's registry extension
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos
